name: acquia-74
recipe: acquia
config:
  php: 7.4
  acli_version: 1.30.0

# Instructs Lando to use the local development version of the @lando/acquia plugin
# located at the relative path '../..' from this example's directory.
# This is crucial for testing local plugin changes.
plugins:
  "@lando/acquia": ../..
