name: acquia-downstreamer-1
recipe: acquia
config:
  php: 8.1
services:
  database:
    type: mysql:8.0

# do not remove this
plugins:
  "@lando/acquia": ../..
  "@lando/mysql": ../../node_modules/@lando/mysql
