name: acquia-xdebug
recipe: acquia
config:
  xdebug: true # Explicitly enable Xdebug for this example

# Instructs Lando to use the local development version of the @lando/acquia plugin
# located at the relative path '../..' from this example's directory.
# This is crucial for testing local plugin changes.
plugins:
  "@lando/acquia": ../..
