name: Drupal Tests

on:
  pull_request:

jobs:
  leia-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
      ACQUIA_API_KEY: ${{ secrets.ACQUIA_API_KEY }}
      ACQUIA_API_SECRET: ${{ secrets.ACQUIA_API_SECRET }}
      RUN_ID: ${{ github.sha }}${{ github.run_id }}${{ github.run_number }}
    strategy:
      matrix:
        leia-tests:
          - drupal
        lando-version:
          - 3-dev-slim
        os:
          - ubuntu-22.04
        node-version:
          - '18'

    steps:
      # Install deps and cache
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install NPM dependencies
        run: npm clean-install --production --production --prefer-offline --frozen-lockfile
      - name: Bundle Deps
        uses: lando/prepare-release-action@v2
        with:
          lando-plugin: true
          version: dev
          sync: false
      - name: Setup lando ${{ matrix.lando-version }}
        uses: lando/setup-lando@v2
        with:
          lando-version: ${{ matrix.lando-version }}
          config: |
            setup.skipCommonPlugins=true
            setup.plugins.@lando/acquia=/home/runner/work/acquia/acquia
          telemetry: false
      - name: Run Leia Tests
        uses: lando/run-leia-action@v2
        with:
          leia-test: "./examples/${{ matrix.leia-tests }}/README.md"
          cleanup-header: "Destroy tests"
          shell: bash
          stdin: true
