name: Drupal Tests

on:
  pull_request:

jobs:
  leia-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
      ACQUIA_API_KEY: ${{ secrets.ACQUIA_API_KEY }}
      ACQUIA_API_SECRET: ${{ secrets.ACQUIA_API_SECRET }}
      RUN_ID: ${{ github.sha }}${{ github.run_id }}${{ github.run_number }}
    strategy:
      fail-fast: false
      matrix:
        leia-test:
          - examples/drupal
        lando-version:
          - 3-dev-slim
        os:
          - ubuntu-22.04
        node-version:
          - '16'

    steps:
      # Install deps and cache
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
          cache: npm
      - name: Install NPM dependencies
        run: npm clean-install --prefer-offline --frozen-lockfile
      - name: Setup lando ${{ matrix.lando-version }}
        uses: lando/setup-lando@v2
        with:
          lando-version: ${{ matrix.lando-version }}
          config: |
            plugins.@lando/acquia=/home/runner/work/acquia/acquia
          telemetry: false
      - name: Verify Lando works and we are dogfooding this plugin for tests
        run: |
          lando version
          lando config --path plugins | grep acquia | grep /home/runner/work/acquia/acquia || (echo "::error:: Not dogfooding this plugin correctly!" && exit 1)
      - name: Run Leia Tests
        uses: lando/run-leia-action@v2
        with:
          leia-test: "./${{ matrix.leia-test }}/README.md"
          cleanup-header: "Destroy tests"
          shell: bash
          stdin: true
